### ISSUE TITLE
Number of classes, 42, does not match size of target_names, 43. Try specifying the labels parameter.

### ISSUE THREAD

**Issue by ekinburak** [etano/productner#11]
@etano , thanks for sharing! 

--THIS IS NOT A BUG--

I have a question related how to solve this: 
`ValueError: Number of classes, 42, does not match size of target_names, 43. Try specifying the labels parameter`

As it is coded, I am having this after I ran
`python train_classifier.py data/products.normalized.trimmed.supplemented.tagged.csv`

I believe the error is coming cuz of empty class in JSON (" "). How can I get rid of ? Should I get rid of ? Should I ignore ? 

Can you please guide me in this matter ? 

Cheers,

**Comment by rbhambriiit** [comment]
This might help:
https://github.com/scikit-learn/scikit-learn/issues/7751

**Comment by ikvision** [comment]
In case the unique classes in train and validation are a different number the classifcation_report fails by default
Line https://github.com/etano/productner/blob/master/classifier.py#L205 need to be fixed by adding labels
as in 
`print((classification_report(y_val, predicted_classes, target_names=target_names, digits = 6,labels=range(len(self.category_map)))))`

**Comment by Abonia1** [comment]
I do have the same error saying :
ValueError: Number of classes, 5, does not match size of target_names, 10. Try specifying the labels parameter.

I really dont want to open new issue cause there exist motre than 5 issues concern with this value error in classification_report :(

**Comment by etano** [comment]
@ikvision can you make a PR?

**Comment by ikvision** [comment]
I did a pull request with my changes
